
insert into `api_method` (`type`, `name`, `uri`, `mask_uri`, `method`, `schema`, `description`, `plugin_identifier`, `order`, `type_id`, `is_active`, `is_token_required`, `created_at`) values('get','Extension : {plugin_name} : Tag : Listing','{api_base_route}/tag/listing','','',NULL,'API call to retrieve available post tags','ext_post','2','0','1','0','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/listing','get','required','int','target_entity_type_id','Target Entity Type ID','option','0','1','string','sys_entity_type','0',NULL,NULL,'entity_type_id','0','','1','1','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/listing','get','required','int','actor_entity_type_id','Actor Entity Type ID','option','0','1','string','sys_entity_type','0',NULL,NULL,'entity_type_id','0','','1','2','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/listing','get','optional','text','title','Title','text','0','1','string','','0',NULL,NULL,NULL,'0','','1','3','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/listing','get','optional','text','identifier','Identifier','text','0','1','string','','0',NULL,NULL,NULL,'0','','1','4','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/listing','get','optional','int','actor_entity_id','Entity ID that introduced tag','text','0','1','integer','','0',NULL,NULL,NULL,'0','','1','5','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/listing','get','optional','int','count_usage_from','Usage Count (from)','text','0','1','integer','','0',NULL,NULL,NULL,'0','','1','6','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/listing','get','optional','int','count_usage_to','Usage Count(to)','text','0','1','integer','','0',NULL,NULL,NULL,'0','','1','7','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/listing','get','optional','text','order_by','Order by (def:created_at,title,identifier)','text','0','1','string','','0',NULL,NULL,NULL,'0','','1','8','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/listing','get','optional','text','sorting','Sorting (def:desc,asc)','text','0','1','string','','0',NULL,NULL,NULL,'0','','1','9','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/listing','get','optional','int','offset','Offset (def:0)','text','0','1','integer','','0',NULL,NULL,NULL,'0','','1','10','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/listing','get','optional','int','limit','Limit (def:10)','text','0','1','integer','','0',NULL,NULL,NULL,'0','','1','11','{wildcard_datetime}');




insert into `api_method` (`type`, `name`, `uri`, `mask_uri`, `method`, `schema`, `description`, `plugin_identifier`, `order`, `type_id`, `is_active`, `is_token_required`, `created_at`) values('post','Extension : {plugin_name} : Tag : Post','{api_base_route}/tag','','',NULL,'API call to create a tag','ext_post','3','0','1','0','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag','post','required','int','target_entity_type_id','Target Entity Type ID','option','0','1','string','sys_entity_type','0',NULL,NULL,'entity_type_id','0','','1','1','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag','post','required','int','actor_entity_type_id','Actor Entity Type ID','option','0','1','string','sys_entity_type','0',NULL,NULL,'entity_type_id','0','','1','2','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag','post','required','int','actor_entity_id','Actor entity ID','text','0','1','integer','','0',NULL,NULL,NULL,'0','','1','3','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag','post','required','text','title','Title','text','0','1','string','','0',NULL,NULL,NULL,'0','','1','4','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag','post','required','text','identifier','Identifier (should be unique) (slug format only - no special characters)','text','0','1','string','','0',NULL,NULL,NULL,'0','','1','5','{wildcard_datetime}');




insert into `api_method` (`type`, `name`, `uri`, `mask_uri`, `method`, `schema`, `description`, `plugin_identifier`, `order`, `type_id`, `is_active`, `is_token_required`, `created_at`) values('post','Extension : {plugin_name} : Tag : Update','{api_base_route}/tag/update','','',NULL,'API call to update a tag','ext_post','4','0','1','0','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/update','post','required','int','target_entity_type_id','Target Entity Type ID','option','0','1','string','sys_entity_type','0',NULL,NULL,'entity_type_id','0','','1','1','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/update','post','required','int','actor_entity_type_id','Actor Entity Type ID','option','0','1','string','sys_entity_type','0',NULL,NULL,'entity_type_id','0','','1','2','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/update','post','required','int','post_tag_id','Post Tag ID','text','0','1','integer','','0',NULL,NULL,NULL,'0','','1','3','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/update','post','required','int','actor_entity_id','Actor entity ID','text','0','1','integer','','0',NULL,NULL,NULL,'0','','1','4','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/update','post','required','text','title','Title','text','0','1','string','','0',NULL,NULL,NULL,'0','','1','5','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/update','post','required','text','identifier','Identifier (should be unique) (slug format only - no special characters)','text','0','1','string','','0',NULL,NULL,NULL,'0','','1','6','{wildcard_datetime}');





insert into `api_method` (`type`, `name`, `uri`, `mask_uri`, `method`, `schema`, `description`, `plugin_identifier`, `order`, `type_id`, `is_active`, `is_token_required`, `created_at`) values('post','Extension : {plugin_name} : Tag : Delete','{api_base_route}/tag/delete','','',NULL,'API call to delete a tag','ext_post','5','0','1','0','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/delete','post','required','int','target_entity_type_id','Target Entity Type ID','option','0','1','string','sys_entity_type','0',NULL,NULL,'entity_type_id','0','','1','1','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/delete','post','required','int','actor_entity_type_id','Actor Entity Type ID','option','0','1','string','sys_entity_type','0',NULL,NULL,'entity_type_id','0','','1','2','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/delete','post','required','int','post_tag_id','Post Tag ID','integer','0','1','integer','','0',NULL,NULL,NULL,'0','','1','3','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/delete','post','required','int','actor_entity_id','Actor entity ID','text','0','1','string','','0',NULL,NULL,NULL,'0','','1','4','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/delete','post','optional','int','override_access','Override Access (forces delete without actor ID) (def:0,1)','integer','0','1','string','','0',NULL,NULL,NULL,'0','','1','5','{wildcard_datetime}');




insert into `api_method` (`type`, `name`, `uri`, `mask_uri`, `method`, `schema`, `description`, `plugin_identifier`, `order`, `type_id`, `is_active`, `is_token_required`, `created_at`) values('get','Extension : {plugin_name} : Tag : Get','{api_base_route}/tag','','',NULL,'API call to get a tag','ext_post','6','0','1','0','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag','get','required','int','target_entity_type_id','Target Entity Type ID','option','0','1','string','sys_entity_type','0',NULL,NULL,'entity_type_id','0','','1','1','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag','get','required','int','actor_entity_type_id','Actor Entity Type ID','option','0','1','string','sys_entity_type','0',NULL,NULL,'entity_type_id','0','','1','2','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag','get','required','int','post_tag_id','Post Tag ID','integer','0','1','integer','','0',NULL,NULL,NULL,'0','','1','3','{wildcard_datetime}');




insert into `api_method` (`type`, `name`, `uri`, `mask_uri`, `method`, `schema`, `description`, `plugin_identifier`, `order`, `type_id`, `is_active`, `is_token_required`, `created_at`) values('post','Extension : {plugin_name} : Tag : Post or Get','{api_base_route}/tag/post_or_get','','',NULL,'API call to retrieve data (save if not exists)','ext_post','7','0','1','0','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/post_or_get','post','required','int','target_entity_type_id','Target Entity Type ID','option','0','1','string','sys_entity_type','0',NULL,NULL,'entity_type_id','0','','1','1','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/post_or_get','post','required','int','actor_entity_type_id','Actor Entity Type ID','option','0','1','string','sys_entity_type','0',NULL,NULL,'entity_type_id','0','','1','2','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/post_or_get','post','required','int','actor_entity_id','Actor entity ID','text','0','1','string','','0',NULL,NULL,NULL,'0','','1','3','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/post_or_get','post','required','text','title','Title','text','0','1','string','','0',NULL,NULL,NULL,'0','','1','4','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/tag/post_or_get','post','required','text','identifier','Identifier (slug format only - no special characters)','text','0','1','string','','0',NULL,NULL,NULL,'0','','1','5','{wildcard_datetime}');