insert into `api_method` (`type`, `name`, `uri`, `method`, `schema`, `description`, `plugin_identifier`, `order`, `type_id`, `is_active`, `is_token_required`, `created_at`) values('post','Extension : {plugin_name} : Form : Fields : Post (define rules)','{api_base_route}/form/field','',NULL,'API call to define form fields and rules','{plugin_identifier}','3','0','1','0','{wildcard_datetime}') ON DUPLICATE KEY UPDATE updated_at = '{wildcard_datetime}';

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field','post','required','int','actor_entity_type_id','Actor Entity Type ID','option','string','sys_entity_type','0',NULL,NULL,'entity_type_id','1','1','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field','post','required','int','actor_entity_id','Actor Entity ID','text','string','','0',NULL,NULL,NULL,'1','2','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field','post','required','text','entity_type_form_map_id','Entity Type to Form Mapping ID','integer','string','','0',NULL,NULL,NULL,'1','3','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field','post','required','text','field_type_id','Field Type ID','option','integer','fb_field_type','0',NULL,NULL,'field_type_id','1','4','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field','post','required','text','field_name','Field name','text','string','','0',NULL,NULL,NULL,'1','4.1','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field','post','required','text','title','Title','text','string','','0',NULL,NULL,NULL,'1','5','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field','post','optional','text','description','Description','text','string','','0',NULL,NULL,NULL,'1','6','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field','post','optional','text','hint','Hint','text','string','','0',NULL,NULL,NULL,'1','7','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field','post','optional','text','html5_input_type','HTML5 input type for default validation','text','string','','0',NULL,NULL,NULL,'1','8','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field','post','optional','text','js_validation_type','Validation type (def:default,regex,cusotm)','text','string','','0',NULL,NULL,NULL,'1','9','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field','post','optional','text','js_validation_rule','Validation rule (regex or custom script)','text','string','','0',NULL,NULL,NULL,'1','10','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field','post','optional','text','js_validation_event','Validation Event (onblur,onchange,onclick,onfocus,onselect)','text','string','','0',NULL,NULL,NULL,'1','11','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field','post','optional','text','php_validation_type','Validation type (def:default,regex,cusotm)','text','string','','0',NULL,NULL,NULL,'1','12','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field','post','optional','text','php_validation_rule','Validation rule (regex or custom script)','text','string','','0',NULL,NULL,NULL,'1','13','{wildcard_datetime}');




insert into `api_method` (`type`, `name`, `uri`, `method`, `schema`, `description`, `plugin_identifier`, `order`, `type_id`, `is_active`, `is_token_required`, `created_at`) values('get','Extension : {plugin_name} : Form : Fields : Listing','{api_base_route}/form/field/listing','',NULL,'API call to retrive form fields','{plugin_identifier}','5','0','1','0','{wildcard_datetime}') ON DUPLICATE KEY UPDATE updated_at = '{wildcard_datetime}';

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field/listing','get','required','int','entity_type_form_map_id','Entity Type-Form Mapping ID','integer','integer','','0',NULL,NULL,NULL,'1','1','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field/listing','get','optional','int','field_type_id','Field Type','option','integer','fb_field_type','0',NULL,NULL,'field_type_id','1','2','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field/listing','get','optional','text','title','Field Title','text','string','','0',NULL,NULL,NULL,'1','2.1','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field/listing','get','optional','text','field_name','Field Name','text','string','','0',NULL,NULL,NULL,'1','3','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field/listing','get','optional','text','html5_input_type','HTML5 input type','text','string','','0',NULL,NULL,NULL,'1','4','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field/listing','get','optional','text','js_validation_type','Validation Type (def:default,regex,cusotm)','text','string','','0',NULL,NULL,NULL,'1','5','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field/listing','get','optional','text','php_validation_type','Validation Type (def:default,regex,cusotm)','text','string','','0',NULL,NULL,NULL,'1','6','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field/listing','get','optional','text','order_by','Order by (def:created_at)','text','string','','0',NULL,NULL,NULL,'1','7','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field/listing','get','optional','text','sorting','Sorting (def:desc,asc)','text','string','','0',NULL,NULL,NULL,'1','8','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field/listing','get','optional','text','offset','Offset (def:0)','integer','integer','','0',NULL,NULL,NULL,'1','9','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/field/listing','get','optional','text','limit','Limit (def:10)','integer','integer','','0',NULL,NULL,NULL,'1','10','{wildcard_datetime}');