insert into `api_method` (`type`, `name`, `uri`, `method`, `schema`, `description`, `plugin_identifier`, `order`, `type_id`, `is_active`, `is_token_required`, `created_at`) values('post','Extension : {plugin_name} : Form : Post','{api_base_route}/form','',NULL,'API call to create a form','{plugin_identifier}','2','0','1','0','{wildcard_datetime}') ON DUPLICATE KEY UPDATE updated_at = '{wildcard_datetime}';

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form','post','required','int','actor_entity_type_id','Actor Entity Type ID','option','string','sys_entity_type','0',NULL,NULL,'entity_type_id','1','1','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form','post','required','int','actor_entity_id','Actor Entity ID','text','string','','0',NULL,NULL,NULL,'1','2','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form','post','required','int','target_entity_type_id','Target Entity Type ID','option','string','sys_entity_type','0',NULL,NULL,'entity_type_id','1','3','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form','post','required','int','target_entity_id','Target Entity ID','text','string','','0',NULL,NULL,NULL,'0','4','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form','post','required','text','title','Form Title','text','string','','0',NULL,NULL,NULL,'1','5','2017-11-06 20:27:05');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form','post','optional','text','description','Description','text','string','','0',NULL,NULL,NULL,'1','6','{wildcard_datetime}');



insert into `api_method` (`type`, `name`, `uri`, `method`, `schema`, `description`, `plugin_identifier`, `order`, `type_id`, `is_active`, `is_token_required`, `created_at`) values('get','Extension : {plugin_name} : Form : Listing','{api_base_route}/form/listing','',NULL,'API call to retrieve entity forms','{plugin_identifier}','4','0','1','0','{wildcard_datetime}') ON DUPLICATE KEY UPDATE updated_at = '{wildcard_datetime}';


insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/listing','get','required','int','actor_entity_type_id','Actor Entity Type ID','option','string','sys_entity_type','0',NULL,NULL,'entity_type_id','1','1','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/listing','get','required','int','actor_entity_id','Actor Entity ID','text','string','','0',NULL,NULL,NULL,'1','2','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/listing','get','required','int','target_entity_type_id','Target Entity Type ID','option','string','sys_entity_type','0',NULL,NULL,'entity_type_id','1','3','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/listing','get','optional','text','title','Title','text','string','','0',NULL,NULL,NULL,'1','4','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/listing','get','optional','text','order_by','Order by (def:created_at)','text','string','','0',NULL,NULL,NULL,'1','5','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/listing','get','optional','text','sorting','Sorting (def:desc,asc)','text','string','','0',NULL,NULL,NULL,'1','6','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/listing','get','optional','int','offset','Offset (def:0)','integer','integer','','0',NULL,NULL,NULL,'1','7','{wildcard_datetime}');
insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/form/listing','get','optional','int','limit','Limit (def:10)','integer','integer','','0',NULL,NULL,NULL,'1','8','{wildcard_datetime}');