<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Glimmer</title>
<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css" />

<style>
body {font-family: 'Open Sans', sans-serif;font-size:15px;color:rgb(0,0,0);margin:0;padding:0;line-height: 22px; background:#fff;font-weight:300;word-wrap:break-word;}
.header {text-align:center;background:#231f20;padding:10px;}
h1 {text-align:center;font-weight:300;color:rgb(34,44,47)}
h1 small {font-size:15px;}
h3 {margin-bottom:5px;color:rgb(34,44,47)}
a {color:#000;}
nav ul {background:#231f20;margin:0;padding:10px 0;text-align:center;}
nav ul li {display:inline-block;}
nav ul li a {color:#fff;text-decoration:none;padding:5px;font-size:15px;}
nav ul li a:hover {color:#ccc;}
li {list-style:none;}
section {padding:0 20px;}
section p {margin-top:0;}
ol li p {margin-left:17px;}


</style>
</head>

<body>
<h1>Privacy Policy</h1>

<div class="container">
	<section>
        
        
        
        
        <p><a name="_GoBack" id="_GoBack"></a><strong>GIMMER  PRIVACY POLICY</strong><br />
          <strong>January 2016</strong><br />
          Glimmer (&ldquo;Glimmer,&rdquo; &ldquo;we,&rdquo;  and &ldquo;us&rdquo;) respects the privacy of its users (&ldquo;you&rdquo;) and has developed this  Privacy Policy to show its commitment to protecting your privacy. This Privacy  Policy describes the information we collect, how that information may be used,  with whom it may be shared, and your choices about such uses and disclosures.  We encourage you to read this Privacy Policy carefully before using our  application or services or transacting business with us. By using our website  or application (our &ldquo;Service&rdquo;), you are accepting the practices described in  this Privacy Policy.<br />
          If you have any questions  about our privacy practices, please refer to the end of this Privacy Policy for  information on how to contact us.<br />
  <strong>Information we collect about you</strong><br />
          In General. We may collect  information that can identify you such as your name and email address  (&quot;personal information&quot;) and other information that does not identify  you. We may collect this information through a website or a mobile application.  By using the Service, you are authorizing us to gather, analyze and retain data  related to the provision of the Service. When you provide personal information  through our Service, the information may be sent to servers located in the United  States and countries around the world.<br />
  &nbsp;In order to register as a user with Glimmer,  you will be asked to sign in using your Facebook login. If you do so, you  authorize us to access certain Facebook account information, such as your  public Facebook profile (consistent with your privacy settings in Facebook),  your email address, interests, likes, gender, birthday, education history,  relationship interests, current city, photos, personal description, friend  list, and information about and photos of your Facebook friends who might be  common Facebook friends with other Glimmer users. You will also be asked to  allow Glimmer to collect your location information from your device when you  download or use the Service. In addition, we may collect and store any personal  information you provide while using our Service or in some other manner. This  may include identifying information, such as your name, address, email address  and telephone number, and, if you transact business with us, financial  information. You may also provide us photos, a personal description and  information about your gender and preferences for recommendations, such as  search distance, age range and gender. If you chat with other Glimmer users,  you provide us the content of your chats, and if you contact us with a customer  service or other inquiry, you provide us with the content of that  communication.<br />
  &nbsp;We use various technologies to collect  information from your device and about your activities on our Service.<br />
  &nbsp;We automatically collect information from your  browser or device when you visit our Service. This information could include  your IP address, device ID and type, your browser type and language, the  operating system used by your device, access times, your mobile device&rsquo;s  geographic location while our application is actively running, and the  referring website address.<br />
          Cookies and Use of Cookie  Data. When you visit our Service, we may assign your device one or more cookies  to facilitate access to our Service and to personalize your experience. Through  the use of a cookie, we also may automatically collect information about your  activity on our Service, such as the pages you visit, the time and date of your  visits and the links you click. We or other advertisers may use certain data  collected on our Service to show you Glimmer advertisements on other sites or  applications.<br />
          Pixel tags. We embed pixel  tags (also called web beacons or clear GIFs) on web pages, ads, and emails.  These tiny, invisible graphics are used to access cookies and track user activities  (such as how many times a page is viewed). We use pixel tags to measure the  popularity of our features and services. Ad companies also use pixel tags to  measure the number of ads displayed and their performance (such as how many  people clicked on an ad).<br />
          Mobile Device IDs: If  you're using our app, we use mobile device IDs (the unique identifier assigned  to a device by the manufacturer), or Advertising IDs (for iOS 6 and later),  instead of cookies, to recognize you. We do this to store your preferences and  track your use of our app. Unlike cookies, device IDs cannot be deleted, but  Advertising IDs can be reset in &ldquo;Settings&rdquo; on your iPhone or Android. Ad  companies also use device IDs or Advertising IDs to track your use of the app,  track the number of ads displayed, measure ad performance and display ads that  are more relevant to you. Analytics companies use device IDs to track  information about app usage.<br />
  &nbsp;We may allow service providers, advertising  companies and ad networks, and other third parties to display advertisements on  our Service. These companies may use tracking technologies, such as cookies or  web beacons, to collect information about users who view or interact with their  advertisements. We do not provide any&nbsp;non-anonymized&nbsp;personal information  to third parties. Some of these&nbsp;third-party advertising companies may be  advertising networks that are members of the Network Advertising Initiative,  which offers a single location to opt out of ad targeting from member companies  (<a href="http://www.networkadvertising.org/">www.networkadvertising.org</a>). Opting out will not decrease the number of advertisements you  see.<br />
  <strong>How we use the information we collect</strong><br />
          In general, we may use  information that we collect about you to:<br />
          deliver and improve our products  and services, and manage our business;<br />
          manage your account and  provide you with customer support;<br />
          perform research and  analysis about your use of, or interest in, our or others&rsquo; products, services,  or content;<br />
          communicate with you by  email, postal mail, telephone and/or mobile devices about products or services  that may be of interest to you either from us or other third parties;<br />
          develop, display, and  track content and advertising tailored to your interests on our Service and  other sites, including providing our advertisements to you when you visit other  sites;<br />
          website or mobile  application analytics;<br />
          verify your eligibility  and deliver prizes in connection with contests and sweepstakes;<br />
          enforce or exercise any  rights in our&nbsp;<a href="http://www.gotinder.com/terms">Terms of Use</a>; and<br />
          perform functions or  services as otherwise described to you at the time of collection.<br />
          Job applicants. If your  personal information is submitted through our website when applying for a  position with our company, the information will be used solely in connection  with considering and acting upon your application. We may retain your personal  information, but only for the purpose of considering your application for  current or future available positions. This information, which may include your  name and contact information, prior education and experience, and other  information you provide to us, may be shared with&nbsp;third-party&nbsp;service  providers retained by us to collect, maintain and analyze candidate submissions  for job postings.<br />
          In all circumstances, we  may perform these functions directly or use a third party vendor to perform  these functions on our behalf who will be obligated to use your personal  information only to perform services for us. Also, if you access our Service  from a third party social platform, such as Facebook, we may  share&nbsp;non-personal&nbsp;information with that platform to the extent  permitted by your agreement with it and its privacy settings.<br />
  <strong>With whom we share your information</strong><br />
          Information Shared with  Other Users. When you register as a user of Glimmer, your Glimmer profile will  be viewable by other users of the Service. Other users will be able to view  information you have provided to us directly or through Facebook, such as your  Facebook photos, any additional photos you upload, your first name, your age,  approximate number of miles away, your personal description, and information  you have in common with the person viewing your profile, such as common  Facebook friends and likes. If you swipe right to say &ldquo;yes&rdquo; to a person, you  will be able<br />
          to chat with that person  if they swipe right to you, e.g., when you have a &ldquo;match.&rdquo; If you chat with  your match, of course your match will see the content of your chat.<br />
          Personal information. We  do not share your personal information with others except as indicated in this  Privacy Policy or when we inform you and give you an opportunity to opt out of  having your personal information shared. We may share personal information  with:<br />
          Service providers: We may  share information, including personal and financial information, with third  parties that perform certain services on our behalf. These services may include  fulfilling orders, providing customer service and marketing assistance,  performing business and sales analysis, ad tracking and analytics, member  screenings, supporting our Service functionality, and supporting contests,  sweepstakes, surveys and other features offered through our Service. These  service providers may have access to personal information needed to perform  their functions but are not permitted to share or use such information for any  other purposes.<br />
          Other Situations. We may  disclose your information, including personal information:<br />
          In response to a subpoena  or similar investigative demand, a court order, or a request for cooperation  from a law enforcement or other government agency; to establish or exercise our  legal rights; to defend against legal claims; or as otherwise required by law.  In such cases, we may raise or waive any legal objection or right available to  us.<br />
          When we believe disclosure  is appropriate in connection with efforts to investigate, prevent, or take  other action regarding illegal activity, suspected fraud or other wrongdoing;  to protect and defend the rights, property or safety of our company, our users,  our employees, or others; to comply with applicable law or cooperate with law  enforcement; or to enforce our&nbsp;<a href="http://www.gotinder.com/terms">Terms of Use&nbsp;</a>or other agreements or  policies.<br />
          In connection with a  substantial corporate transaction, such as the sale of our business, a  divestiture, merger, consolidation, or asset sale, or in the unlikely event of  bankruptcy.<br />
          Aggregated and/or&nbsp;non-personal&nbsp;information. We  may use and share&nbsp;non-personal&nbsp;information we collect under any of  the above circumstances. We may also share it with other third parties to  develop and deliver targeted advertising on our Service and on websites or  applications of third parties, and to analyze and report on advertising you see.  We may combine&nbsp;non-personal&nbsp;information we collect with  additional&nbsp;non-personal&nbsp;information collected from other sources. We  also may share aggregated,&nbsp;non-personal&nbsp;information, or personal  information in hashed,non-human&nbsp;readable form, with third parties,  including advisors, advertisers and investors, for the purpose of conducting  general business analysis or other business purposes. For example, we may  engage a data provider who may collect web log data from you (including IP  address and information about your browser or operating system), or place or  recognize a unique cookie on your browser to enable you to receive customized  ads or content. The cookies may re&#64258;ect&nbsp;de-identified demographic or other  data linked to data you voluntarily have submitted to us (such as your email  address), that we may share with a data provider solely in  hashed,&nbsp;non-human&nbsp;readable form. To&nbsp;opt-out&nbsp;of cookies that  may be set by third party data or advertising partners, please go to&nbsp;<a href="http://www.aboutads.info/choices/">http://www.aboutads.info/choices/</a>.<br />
  <strong>Do Not Track Disclosure</strong><br />
          Do Not Track (&ldquo;DNT&rdquo;) is a  privacy preference that users can set in their web browsers. DNT is a way for  users to inform websites and services that they do not want certain information  about their webpage visits collected over time and across websites or online  services. We are committed to providing you with meaningful choices about the  information we collect and that is why we provide the&nbsp;opt-out&nbsp;links  above. However, we do not recognize or respond to any DNT signals, as the  Internet industry works toward defining exactly what DNT means, what it means  to comply with DNT, and a common approach to responding to DNT.<br />
  <strong>Third Party Websites</strong><br />
          There are a number of  places on our Service where you may click on a link to access other websites  that do not operate under this Privacy Policy. For example, if you click on an  advertisement on our Service, you may be taken to a website that we do not  control. These third- party websites may independently solicit and collect  information, including personal information, from you and, in some instances,  provide us with information about your activities on those websites. We  recommend that you consult the privacy statements of  all&nbsp;third-party&nbsp;websites you visit by clicking on the &ldquo;privacy&rdquo; link  typically located at the bottom of the webpage you are visiting.<br />
  <strong>How you can access your information</strong><br />
          If you have a Glimmer  account, you have the ability to review and update your personal information  within the Service by opening your account and going to settings. More  information about how to contact us is provided below. You also may close your  account at any time by visiting the &quot;Settings&quot; page for your account.  If you close your account, we will retain certain information associated with  your account for analytical purposes and recordkeeping integrity, as well as to  prevent fraud, enforce our&nbsp;<a href="http://www.gotinder.com/terms">Terms of Use</a>, take actions we deem necessary to protect the integrity of our  Service or our users, or take other actions otherwise permitted by law. In  addition, if certain information has already been provided to third parties as  described in this Privacy Policy, retention of that information will be subject  to those third parties' policies.<br />
  <strong>Your choices about collection and use of your information</strong><br />
          You can choose not to  provide us with certain information, but that may result in you being unable to  use certain features of our Service because such information may be required in  order for you to register as user; purchase products or services; participate  in a contest, promotion, survey, or sweepstakes; ask a question; or initiate  other transactions.<br />
          Our Service may also  deliver notifications to your phone or mobile device. You can disable these  notifications by going into &ldquo;App Settings&rdquo; on the app or by changing the  settings on your mobile device.<br />
          You can also control  information collected by cookies. You can delete or decline cookies by changing  your browser settings. Click &ldquo;help&rdquo; in the toolbar of most browsers for  instructions.<br />
  <strong>How we protect your personal information</strong><br />
          We take security measures  to help safeguard your personal information from unauthorized access and  disclosure. However, no system can be completely secure. Therefore, although we  take steps to secure your information, we do not promise, and you should not expect,  that your personal information, chats, or other communications will always  remain secure. Users should also take care with how they handle and disclose  their personal information and should avoid sending personal information  through insecure email. Please refer to the Federal Trade Commission's website  at<a href="http://www.ftc.gov/bcp/menus/consumer/data.shtm">http://www.ftc.gov/bcp/menus/consumer/data.shtm&nbsp;</a>for information about how to protect yourself against identity  theft.<br />
  <strong>Information you provide about yourself while using our Service</strong><br />
          We provide areas on our  Service where you can post information about yourself and others and  communicate with others. Such postings are governed by our&nbsp;<a href="http://www.gotinder.com/terms">Terms of Use</a>. Also, whenever you  voluntarily disclose personal information on publicly-viewable&nbsp;pages, that  information will be publicly available and can be collected and used by others.  For example, if you post your email address, you may receive unsolicited messages.  We cannot control who reads your posting or what other users may do with the  information you voluntarily post, so we encourage you to exercise discretion  and caution with respect to your personal information.<br />
  <strong>Children's privacy</strong><br />
          Although our Service is a  general audience Service, we restrict the use of our service to individuals age  18 and above. We do not knowingly collect, maintain, or use personal  information from children under the age of 18.<br />
  <strong>Visiting our Service from outside the United States</strong><br />
          If you are visiting our  Service from outside the United States, please be aware that your information  may be transferred to, stored, and processed in the United States where our  servers are located and our central database is operated. By using our  services, you understand and agree that your information may be transferred to  our facilities and those third parties with whom we share it as described in  this privacy policy.<br />
  <strong>No Rights of Third Parties</strong><br />
          This Privacy Policy does  not create rights enforceable by third parties or require disclosure of any  personal information relating to users of the website.<br />
  <strong>Changes to this Privacy Policy</strong><br />
          We will occasionally  update this Privacy Policy. When we post changes to this Privacy Policy, we  will revise the &quot;last updated&quot; date at the top of this Privacy  Policy. We recommend that you check our Service from time to time to inform  yourself of any changes in this Privacy Policy or any of our other policies.<br />
  <strong>How to contact us</strong><br />
        If you have any questions  about this Privacy Policy, please contact us by email or postal mail as  follows:</p> 
        support@glimmer.com
</section>
</div>
</body>
</html>