insert  into `api_method` (`plugin_identifier`,`type`,`name`,`uri`,`description`,`order`,`is_active`,`created_at`) values
('{plugin_identifier}','post','Extension : {plugin_name} : Comment / Reply : Post','{api_base_route}/comment','API call to post a Comment / Reply',1,1,'{wildcard_datetime}') ON DUPLICATE KEY UPDATE updated_at = '{wildcard_datetime}';

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment','post','required','int','target_entity_type_id','Target Entity Type ID','option','0','1','string','sys_entity_type','0',NULL,NULL,'entity_type_id','0','','1','1','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment','post','required','int','actor_entity_type_id','Actor Entity Type ID','option','0','1','string','sys_entity_type','0',NULL,NULL,'entity_type_id','0','','1','2','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment','post','required','int','target_entity_id','Target Entity ID where activity is being performed','text','0','1','integer','','0',NULL,NULL,NULL,'0','','1','3','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment','post','required','int','actor_entity_id','Actor Entity ID','text','0','1','integer','','0',NULL,NULL,NULL,'0','','1','4','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment','post','optional','int','parent_id','Parent comment ID to post reply','text','0','1','integer','','0',NULL,NULL,NULL,'0','','1','5','{wildcard_datetime}');


insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment','post','optional','text','content','Comment / Reply content','text','0','1','text','','0',NULL,NULL,NULL,'0','','1','6','{wildcard_datetime}');


insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment','post','optional','text','json_data','JSON data (required without review)','text','0','1','text','','0',NULL,NULL,NULL,'0','','1','7','{wildcard_datetime}');




insert  into `api_method`(`plugin_identifier`,`type`,`name`,`uri`,`description`,`order`,`is_active`,`created_at`) values
('{plugin_identifier}','get','Extension : {plugin_name} : Comment / Reply : Listing','{api_base_route}/comment/listing','API call to retrieve entity reviews',1,1,'{wildcard_datetime}') ON DUPLICATE KEY UPDATE updated_at = '{wildcard_datetime}';


insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment/listing','get','required','int','target_entity_type_id','Target Target Entity Type ID','option','0','1','string','sys_entity_type','0',NULL,NULL,'entity_type_id','0','','1','1','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment/listing','get','required','int','actor_entity_type_id','Actor Entity Type ID where activity is being performed','option','0','1','string','sys_entity_type','0',NULL,NULL,'entity_type_id','0','','1','2','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment/listing','get','optional','text','target_entity_id','Target Entity ID (i.e:post,review)','integer','0','1','string','','0',NULL,NULL,NULL,'0','','1','3','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment/listing','get','optional','int','actor_entity_id','Actor Entity ID','text','0','1','integer','','0',NULL,NULL,NULL,'0','','1','4','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment/listing','get','optional','int','package_comment_id','Comment ID to load replies','text','0','1','integer','','0',NULL,NULL,NULL,'0','','1','5','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment/listing','get','optional','text','order_by','Order by (def:created_at,entity_id)','text','0','1','string','','0',NULL,NULL,NULL,'0','','1','6','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment/listing','get','optional','int','sorting','Sorting (def:desc,asc)','text','0','1','string','','0',NULL,NULL,NULL,'0','','1','7','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment/listing','get','optional','int','offset','Offset (def:0)','integer','0','1','string','','0',NULL,NULL,NULL,'0','','1','8','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment/listing','get','optional','int','limit','Limit (def:10)','integer','0','1','string','','0',NULL,NULL,NULL,'0','','1','9','{wildcard_datetime}');




insert  into `api_method` (`plugin_identifier`,`type`,`name`,`uri`,`description`,`order`,`is_active`,`created_at`) values
  ('{plugin_identifier}','post','Extension : {plugin_name} : Comment / Reply : Update','{api_base_route}/comment/update','API call to update a Comment / Reply',1,1,'{wildcard_datetime}') ON DUPLICATE KEY UPDATE updated_at = '{wildcard_datetime}';

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment/update','post','required','int','target_entity_type_id','Target Entity Type ID','option','0','1','string','sys_entity_type','0',NULL,NULL,'entity_type_id','0','','1','1','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment/update','post','required','int','actor_entity_type_id','Actor Entity Type ID','option','0','1','string','sys_entity_type','0',NULL,NULL,'entity_type_id','0','','1','2','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment/update','post','required','int','actor_entity_id','Actor Entity ID','text','0','1','integer','','0',NULL,NULL,NULL,'0','','1','3','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment/update','post','required','int','package_comment_id','Comment / Reply id which needs to be updated','integer','0','1','integer','','0',NULL,NULL,NULL,'0','','1','4','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment/update','post','optional','text','content','Comment / Reply','text','0','1','text','','0',NULL,NULL,NULL,'0','','1','5','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment/update','post','optional','text','json_data','JSON data (required without review)','text','0','1','text','','0',NULL,NULL,NULL,'0','','1','6','{wildcard_datetime}');



insert  into `api_method` (`plugin_identifier`,`type`,`name`,`uri`,`description`,`order`,`is_active`,`created_at`) values
  ('{plugin_identifier}','post','Extension : {plugin_name} : Comment / Reply : Delete','{api_base_route}/comment/delete','API call to delete a Comment / Reply',1,1,'{wildcard_datetime}') ON DUPLICATE KEY UPDATE updated_at = '{wildcard_datetime}';

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment/delete','post','required','int','target_entity_type_id','Target Entity Type ID','option','0','1','string','sys_entity_type','0',NULL,NULL,'entity_type_id','0','','1','1','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment/delete','post','required','int','actor_entity_type_id','Actor Entity Type ID','option','0','1','string','sys_entity_type','0',NULL,NULL,'entity_type_id','0','','1','2','{wildcard_datetime}');


insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment/delete','post','required','int','actor_entity_id','Actor Entity ID','text','0','1','integer','','0',NULL,NULL,NULL,'0','','1','3','{wildcard_datetime}');

insert into `api_method_field` (`method_uri`, `request_type`, `type`, `data_type`, `name`, `description`, `element_type`, `is_read_only`, `is_search`, `element_validation_type`, `depend_table`, `depend_table_id`, `depend_table_where`, `depend_table_title`, `depend_table_value`, `is_entity_auth`, `default_value`, `is_active`, `order`, `created_at`) values('{api_base_route}/comment/delete','post','required','int','package_comment_id','Comment / Reply id which needs to be updated','text','0','1','integer','','0',NULL,NULL,NULL,'0','','1','4','{wildcard_datetime}');
