/*
SQLyog Enterprise v10.42 
MySQL - 5.1.73 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

insert into `api_method` (`type`, `name`, `uri`, `schema`, `description`, `plugin_identifier`, `order`, `is_active`, `is_token_required`, `created_at`) values('post','User : Signup','users',NULL,'API call to insert a user','social_gist','20','1','0','2017-01-11 12:58:39');
insert into `api_method` (`type`, `name`, `uri`, `schema`, `description`, `plugin_identifier`, `order`, `is_active`, `is_token_required`, `created_at`) values('post','User : Confirm Signup','users/confirm_signup',NULL,'API call to verify email signup','social_gist','27','1','0','2017-01-19 17:30:15');
insert into `api_method` (`type`, `name`, `uri`, `schema`, `description`, `plugin_identifier`, `order`, `is_active`, `is_token_required`, `created_at`) values('post','User : Signin','users/signin',NULL,'API call to sign-in user','social_gist','28','1','0','2017-01-20 17:06:24');
insert into `api_method` (`type`, `name`, `uri`, `schema`, `description`, `plugin_identifier`, `order`, `is_active`, `is_token_required`, `created_at`) values('post','User : Forgot Password Request','users/forgot_request',NULL,'API call to retrive new password','social_gist','29','1','0','2017-01-20 17:08:40');
insert into `api_method` (`type`, `name`, `uri`, `schema`, `description`, `plugin_identifier`, `order`, `is_active`, `is_token_required`, `created_at`) values('post','User : Change Password','users/change_password',NULL,'API call to change password','social_gist','28','1','0','2017-03-03 02:05:53');
insert into `api_method` (`type`, `name`, `uri`, `schema`, `description`, `plugin_identifier`, `order`, `is_active`, `is_token_required`, `created_at`) values('post','User : Edit Profile','users/edit_profile',NULL,'API call to edit profile','social_gist','29','1','0','2017-03-06 03:00:28');
insert into `api_method` (`type`, `name`, `uri`, `schema`, `description`, `plugin_identifier`, `order`, `is_active`, `is_token_required`, `created_at`) values('post','User : Social Login','users/social_login',NULL,'API call to login user via Social Platforms','social_gist','28.1','1','0','2017-03-21 08:49:51');
insert into `api_method` (`type`, `name`, `uri`, `schema`, `description`, `plugin_identifier`, `order`, `is_active`, `is_token_required`, `created_at`) values('post','User : Save Token','users/save_token',NULL,'API call to save user device token for Push Notification','social_gist','46','1','0','2017-04-10 12:37:56');
insert into `api_method` (`type`, `name`, `uri`, `schema`, `description`, `plugin_identifier`, `order`, `is_active`, `is_token_required`, `created_at`) values('post','User : Verify Phone (Signup/Forgot/Change Mobile No)','users/verify_phone',NULL,'API call to verify phone via Authy','social_gist','47','1','0','2017-05-02 09:45:20');
insert into `api_method` (`type`, `name`, `uri`, `schema`, `description`, `plugin_identifier`, `order`, `is_active`, `is_token_required`, `created_at`) values('post','User : Resend Code (Authy)','users/resend_code',NULL,'API call to resend twilio code','social_gist','48','1','0','2017-05-12 04:26:43');
insert into `api_method` (`type`, `name`, `uri`, `schema`, `description`, `plugin_identifier`, `order`, `is_active`, `is_token_required`, `created_at`) values('post','User : Reset Password','users/reset_password',NULL,'API call to reset password after successful forgot password request','social_gist','50','1','0','2017-05-16 13:46:44');
insert into `api_method` (`type`, `name`, `uri`, `schema`, `description`, `plugin_identifier`, `order`, `is_active`, `is_token_required`, `created_at`) values('post','User : Delete','users/delete',NULL,'API call to delete user','social_gist','48','1','0','2017-05-18 11:16:12');
insert into `api_method` (`type`, `name`, `uri`, `schema`, `description`, `plugin_identifier`, `order`, `is_active`, `is_token_required`, `created_at`) values('post','User : Change ID Request','users/change_id_request',NULL,'API call to change ID (email,mobile_no)','social_gist','49','1','0','2017-05-22 11:35:34');
insert into `api_method` (`type`, `name`, `uri`, `schema`, `description`, `plugin_identifier`, `order`, `is_active`, `is_token_required`, `created_at`) values('post','User : Reset ID','users/reset_id',NULL,'API call to reset ID (email,mobile_no)','social_gist','50','1','0','2017-05-22 14:40:41');
insert into `api_method` (`type`, `name`, `uri`, `schema`, `description`, `plugin_identifier`, `order`, `is_active`, `is_token_required`, `created_at`) values('post','User : Logout','users/logout',NULL,'API call to reset ID (email,mobile_no)','social_gist','51','1','0','2017-05-22 14:40:41');
